@startuml C4_Elements
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(miner1, "Miner 1", "Mining Operation")
Person(miner2, "Miner 2", "Mining Operation")
Person(miner3, "Miner 3", "Mining Operation")
Person(miner4, "Miner 4", "Mining Operation")

System_Boundary(s, "Federation") {
    Person(federation_a, "Member A", "Federation member")
    Person(federation_b, "Member B", "Federation member")
    Person(federation_c, "Member C", "Federation member")
}

BiRel_D(miner1, federation_a, "Uses", "Stratum")
BiRel_D(miner2, federation_a, "Uses", "Stratum")
BiRel_D(miner2, federation_a, "Uses", "Stratum")
BiRel_D(miner3, federation_b, "Uses", "Stratum")
BiRel_D(miner4, federation_b, "Uses", "Stratum")

BiRel_R(federation_a, federation_b, "replication", "p2p commnication")
BiRel_R(federation_a, federation_c, "replication", "p2p communication")
BiRel_D(federation_b, federation_c, "replication", "p2p communication")
