@startuml

skinparam componentStyle rectangle

[component]

component "Federation Member A" {
	component btc.a [
	Bitcoin Node
	]
	component sreg.a [
	Stratum Registration
	]
 	component smine.a [
	Stratum Mining API
	]
	component fnet.a [
	Federation Network
	]
}

sreg.a -[hidden]> smine.a
btc.a -[hidden]> fnet.a
btc.a --[hidden]> sreg.a

component "Federation Member B" {
	component btc.b [
	Bitcoin Node
	]
	component sreg.b [
	Stratum Registration
	]
 	component smine.b [
	Stratum Mining API
	]
	component fnet.b [
	Federation Network
	]
}

sreg.b -[hidden]> smine.b
fnet.b -[hidden]> btc.b
btc.b --[hidden]> sreg.b

component "Miner 1" {
	component scli.1 [
	Miner Console
	]
	component sclient.1 [
	Stratum Mining Client
	]
}

component "Miner 2" {
	component scli.2 [
	Miner Console
	]
	component sclient.2 [
	Stratum Mining Client
	]
}

fnet.a <-> fnet.b

sreg.a <--> scli.1
sreg.b <--> scli.2

smine.a <--> sclient.1

smine.b <--> sclient.2

scli.1 -[hidden]> sclient.1
scli.2 -[hidden]> sclient.2

sreg.a <--[hidden]> scli.1
sreg.b <--[hidden]> scli.2

hide @unlinked
@enduml
