= Attacks

We describe some of the attacks and how Radpool resists them.

== Block Withholding Attacks

Each syndicate miner builds templates for the miners working
with it. The problem of block witholding attack is not made worse like
it is in the case of Braidpool where miners build their own block
templates.

Each MSP also validates all the shares it receives from the miners and
from other MSPs. That is, a share is earmarked to be rewarded only if
it passes share validation agains the block template the syndicate
miner generated.

The reward calculation algorithm deducts rewards from all miners to
give a bonus to the miner that found the block. As show by
https://link.springer.com/article/10.1007/s10878-021-00768-4[Zhihuai
Chen et. al.] such an approach discourages block withholding attacks.

== Sybil Attacks As MSP

When a miner sends their share to a MSP, the member signs the shares
before broadcasting to the entire syndicate. This identifies shares
with the MSPs that brought the hashrate to the pool.

To prevent anyone from joining the syndicate by bringing in capital,
we require that MSPs also bring in hashrate to the pool. Further, to
resist sybil attacks by anyone joining the syndicate, we limit the
threshold participation to the members that bring the top 65% of the
hashrate as explained in <<Membership>>.

== DDoS Attacks by MSP

== Fluctuating Hashrate Attack

An MSP can bring a lot of hashrate to Radpool and then quickly take it
away suddenly. Such an MSP could be another pool on bitcoin that wants
to attack Radpool. The attack seems to work because it seems like as
the Radpool hashrate increases the miners payout also
increases. However, this is a fallacy, as the miner is always paid
based on its own hashrate, not based the Radpool hashrate. Even if the
total amount earned by Radpool increases due to an increase in the
hashrate, the amount paid to individual miner is only related to the
individual miner's hashrate. When Radpool's hashrate increases, the
variance in the payouts to miners reduces, not the amounts paid.
