= Bitcoin Contracts
:stem: latexmath

These page shows the various bitcoin contracts used by the Radpool
payout mechanism.

== Coinbase

The coinbase pays the syndicate public key, called the **syndicate
public key**, stem:[S_{pk}], is generated using the FROST KeyGen
protocol as described in the
xref:frost-federation.adoc#_membership[Membership] section of
xref:frost-federation.adoc[FROST Federation] page.

This coinbase is spent using an interactive protocol between the MSPs
when signatures for all miner DLC contracts have been generated by the
syndicate. The interactive protocol is described in the
xref:msp-protocols.adoc[MSP Protocols] page.

== DLC Contracts Between Miner and MSP

Each miner enters a DLC contract with the MSP that funds the miner's
operations. In this section we describe the details of the bitcoin
cointract.

=== Funding Contract

The miner and the MSP create a funding transaction that spends the
MSP's UTXO into a 2 of 2 multisig. The funding output between the
miner stem:[m] and the stem:[msp] is refered to as stem:[F_{m,msp}].

==== Nonce and Oracle Public Key For Miners

DLCs require an oracle to publish the public nonce (stem:[R] value)
and the public key (stem:[P] value) for generating signatures that
settle the DLC. These stem:[R] and stem:[P] values are published for
each miner when the miner registers with an MSP.

We add a subscript to these values to highlight that they are
generated for each DLC contract between a miner and the MSP. Therefore
the contract between miner stem:[m] and MSP stem:[msp] uses
stem:[R_{m,msp}] and stem:[P_{m,msp}] values.

stem:[R_{m,msp}]:: The nonce for DLC contract is generated by MSP and
published to syndicate using the reliable BFT protocol. The DLC specs
point out that centralised generation of this nonce is acceptable.

stem:[P_{m,msp}]:: The public key for the DLC Oracle is generated
using a DKG instance when the miner registers with an MSP. This
requires that an MSP can request the syndicate to run a DKG instance
for every miner that joins.

=== Contract Execution Transaction (CETs)

A number of CETs are generated by the two parties, matching the range
of contract settlement terms. Each of the CET requires a signature
from Radpool syndicate. The syndicate signs a message that is a
representation of the exchange rate between the miner's hashrate and
the BTC offered by the MSP, let's call this exchange rate
stem:[E_{m,msp}], i.e. the exchange rate between the miner stem:[m]
and the MSP stem:[msp].

DLC requires that the miner and the MSP generate a number of CETs
corresponding to a range over the exchange rate. We write the
stem:[i^{th}] exchange rate as stem:[E_{i,m,msp}].

The public keys of miner stem:[m] and MSP stem:[msp] are tweaked using
the the exchange range as:

. stem:[Pub_{i,m} = Pub_m + s_{i,m,msp}G] and
. stem:[Pub_{i,msp} = Pub_{msp} + s_{i,m,msp}G]

Using the above public keys two CETs are generated that spend the
funding output stem:[F_{m,msp}] - one for each party.

The miner and the MSP have a CET each with the spending conditions:

Miner:: stem:[Pub_{i,m} \lor (Pub_{msp} \wedge TimeDelay)]
MSP:: stem:[Pub_{i,msp} \lor (Pub_{m} \wedge TimeDelay)]

Both the miner and MSP thus have a non-custodial UTXO they can spend
as soon as Radpool signs the hashrate on the pool.

=== Radpool Syndicate Generates Oracle Signature

The Radpool syndicate acts as the oracle for paying out miners and
signs a message that corresponds to each miner's hashrate over the
last known periods. The oracle doesn't know the terms of the contracts
and therefore has to publish signatures for a well known range of
expiry timestamps. For example, the Radpool syndicate can publish the
hashrate of all miners over the last 1 day, 1 week and 1 month.

The signature is generated using the FROST Federation threshold
signature. The threshold signature can be run in a single round as
described section
xref:frost-federation.adoc#_federation_signature_in_single_round[Federation
Signature in Single Round].

The Radpool oracle publishes a threshold signature,
stem:[s_{i,m,msp}], that corresponds to the following:

stem:[s_{i,m,msp} = k_m - h(E_{i,m,msp}, R_m)v_m]

stem:[k_m]:: known, as it is broadcast using a BFT reliable broadcast
by the MSP when it generates stem:[R_{m,msp}].

stem:[E_{i, m, msp}]:: known, from the local store on all MSP, again
  thanks to a reliable BFT broadcast that provides consistent
  information dispersal.
stem:[v_m]:: not known, is the private key corresponding to the public
  key stem:[P_{m,msp}].

Radpool is thus able to perform the functions of a DLC Oracle without
any single party holding the private key, and requiring a minimum
threshold number of parties to co-operate.


=== Series of DLCs For Each Expiry Period

The miner and the MSP enter a contract for each expiry period. For
example, if a miner wants to be paid on a weekly basis, they enter
into a DLC contract at the start of each week. So a sequence of
contracts can look like the table below. Each of the contract will
have the full range of CETs that pay the miner a set amount of BTC for
the various values of hashrate it generates.

.Sequence of contracts between a miner and MSP
[cols="1,1,1"]
|===
| Week | Hashrate (PH/s) | Amount (sats)

| Aug 1 | 1 | 1,000,000

| Aug 8 | 1 | 1,000,000

| Aug 15 | 1 | 1,000,000
|===

Each week's contract is created just before the expiry of the previous
week's contract. The MSP calculates the BTC amount to pay for the
hashrate and offers a contract. The miner can provide configuration
options to set the minimum payout it is willing to accept for the
hashrate. How the MSP calculates the BTC to pay for hashrate is not
addressed here. We expect there will be plugins that offer various
means and models to compute this exchange rate.

=== Rollover Miner Payout

The miner can spend the contract output without requiring a signature
from the MSP or the syndicate. However, spending a CET and then
another transaction to spend the non-custodial UTXO on chain each time
the miner earns a payout will not scale. We will need to use up block
space per miner for each expiry period. Instead, we propose that
miners and MSPs rollover ther balance into the next DLC contract for
the next payout period. The roll-over will work similar to the way LN
contract state is expired to be replace with a new one, as describe in
the
xref:payout-mechanism.adoc#_roll_over_contract_transactions[Roll-Over
Contract Transaction] section.
