= Capital Requirements For MSPs

The capital required to fund the pool is distributed across the MSPs
reducing the capital risks for any individual
MSP. Each miner's payout is pre-funded by a syndicate member. The
terms and fees are agreed upon between the two parties and the
syndicate does not impose any requirements on these terms.

== Match Making

One miner thus chooses a syndicate that funds their payout
contract. This match making between MSP and miner happens on mailing
lists, forums or OTC between the two parties.

Each syndicate funds payout contracts for a set of miner. Therefore
the capital requirement for each MSP is related to the hashrate the
miners bring to the pool. The Radpool syndicate has no view on the DLC
contracts between the MSP and the miner. Radpool's miner dashboard
provides a view in to the balance and allows the contracts to be
extended, or the miner can get into a contract with another MSP.

== Incentives to Grow The Syndicate

When a new member joins a syndicate, the existing members will see
reduced earnings because the block reward is now distributed between
more miners and the fees are also distributed across more syndicate
members. The syndicate however is still incentivized to include a new
MSPs as a larger syndicate will be able to manage payouts for larger
number of miners. A larger set of miners thus reduce variance even
further. This flywheel effect is important for any syndicate to try
and achieve and thus expanding the size of the syndicate is important
for increased profits for the entire syndicate.

[TODO] Add the "grow the pie" chart.
