= Federation Protocols

The federation and miners follow a number of separate protocols to
enable the system to work together.

== Initial Setup

To start a new federation, any member announces their network
address. The threshold and federation size is set to one.

Miners that want to join the federation initiate their registration
with sole federation member and set their stratum end point to the
federation member.

.New federation with single member
[plantuml, target=intial-setup]
....
@startuml
Miner --> FederationMember: Register
FederationMember --> Miner: Auth token
Miner <--> FederationMember: Stratum auth, notify, submit
"Miner/Validtor" <-- FederationMember: Share broadcasts
@enduml
....

At this point, the sole federation member acts like a centralised pool
operator, with transparent share accounting.

== New Federation Member

To join the federation, a new member has to lock in capital in to a
bitcoin transaction signed by the Federation using a Schnorr threshold
signautre. A successfully signed transaction signifes that a threshold
of the existing federation member agree to the new member joining.

The only criterion available for the existing federation members is the
amount of new capital the new member is bringing to the federation.

Each federation can decide the policies they want to adopt for
admitting new members by agreeing on the minimum and maximum bitcoin
that each member locks into the federation. This value is agreed out of
band and configured at federation start up time.

.New federation member
[plantuml, target=intial-setup]
....
@startuml
NewFederationMember --> ExistingMember: Join Request
ExistingMember <--> Federation: Reliable broadcast of Join Request
ExistingMember --> NewFederationMember: New funding tx (unsigned)
NewFederationMember --> ExistingMember: Partially signed funding tx
NewFederationMember <--> Federation: Run FROST to sign new tx
@enduml
....

== Federation Member Exit

Similar to the protocol followed to add a new member to the federation,
the federation members create a new transaction with updated
balances. The member leaving the federation is part of the party that
runs the threshold signature instance to sign the input spending the
previous federation output.

== Federation Member Failures

If a member fails (say is unresponsive), the federation continues to
operate as normal. If more than a threshold number of federation
members fail, the pool reaches end of life and all federation members
along with miners can claim their outputs after the timeout expiry.

See section on Bitcoin Contracts to see how the transactions are
structured.

