= Federation Network

The federation members open a point to point to connection with all
other federation members. This channels is authenticated and
confidential.

Each federation member sends the following messages to all other
federation members:

. New block template it is working on
. The stratum job it sends to miners
. All shares received from all miners
. Requests by new federation members
. Miner public key once it is registered with the federation member
. Requests received from miners to leave the pool

The messages above will result in subsantial amount of network
traffic. The federation members also validate all the shares received
from other federation members.

The replication of shares on all federation members is important
because this transparent share accounting enables all the miners to
calculate the payout distribution and validate any new payout and
coinbase transactions before signing the federation update transaction.

== Share Replication and Accounting

Once a miner starts sending shares to a federation member, the shares
are replicated to the other federation members. A federation member that
receives shares, verifies the shares before broadcasting it to the
rest of the federation.

A miner can send their shares to multiple federations by registering
with the federation.
