= Fedpool - Federated Mining Pool

Current mining pools provide no visibility to miners on the share
accounting or the fees charged by the pool. Further still, the current
pools are vulnerable to attacks where they can be forced to follow
transaction selection rules. On the other hand, P2P pools like
Braidpool attempt to solve the transaction selection problem but their
use requires miners to run extra services on premise. Some of these
services are not easy to boot up and maintain. This friction can leave
the long tail of miners out of the P2P pool. These long tail of miners
are important to bitcoin for resisting censorship attacks.

In this document we present a mining pool solution that uses a
federation to replace the centralised pool operator. Federation
members generate block templates and provide stratum end points to
miners. Since federation tracks miner's shares in an open P2P network,
anyone, including the miners can validate the share accounting and
reward distribution results.

We show a construction where the federation members distribute rewards
to miners in a way that miners can unilaterally exit from the pool
with their coins. We also show that federation members can not steal
miner's shares or reward.
