= Syndicate Membership

Group membership has a reduction to consensus. In our trust model, we
require this consensus to have byzantine fault tolerant
properties. This makes it hard to track who are the current members of
the syndicate. To solve the problem, we turn to using Bitcoin
consensus for maintaining the syndicate membership.

Syndicate members provide inputs into a membership transaction. The
outputs of the membership transaction require the syndicate threshold
signature to spend and carry a dust amount. The outputs of the
membership transaction are used as inputs into funding transactions
that manage the payouts made to miners.

By requiring a bitcoin transaction to be confirmed and have certain
minimum confirmations, we solve the syndicate's membership problem
using bitcoin's BFT consensus.


== Syndicate Membership Transaction

The diagram below shows three syndicate members, each with two
miners. The transaction construction shows that syndicates lock in
their capital and generate UTXOs that are used to fund payout channels
to miners.

TODO: Add diagram and an explanation
