= Syndicate Membership

We use the bitcoin consensus mechanism to decide on the syndicate
membership and the FROST DKG to reach a consensus on the current
syndicate membership.

Membership requires a consensus protocol and in our case this needs to
be a byzantine fault tolerant consensus. We also need syndicates to
lock in capital for payouts to miners.

We use a confirmed bitcoin transasction to determine the current
syndicate membership. Syndicate members provide inputs into a
membership transaction. The outputs of the membership transaction
require the syndicate threshold signature to spend and carry a dust
amount. The outputs of the membership transaction are used as inputs
into funding transactions that manage the payouts made to miners.

By requiring a bitcoin transaction to be confirmed and have certain
minimum confirmations, we solve the syndicate's membership problem
using bitcoin's BFT consensus.

The section on link:frost-federation.adoc[FROST Federation] describes
the transaction and the protocols required.
