= Syndicate Network

[TODO] Add network diagem showing unicast and broadcast channels.

The MSPs open a point to point connection with all other MSPs. These
channels are authenticated and confidential. We need point to point
communication channels between MSPs as the FROST threshold signature
protocol requires this and we want to conform with the requirements to
avoid any security weaknesses.

Each MSP sends the following message types to all other MSPs:

. New block template it is working on
. The stratum job it sends to miners
. All shares received from all miners
. Requests by new MSPs
. Miner public key once it is registered with the MSP
. Requests received from miners to leave the pool

All of the above messages are sent using **reliable, authenticated and
secret** communication channels. Our current implementation of
https://github.com/pool2win/frost-federation[FROST Federation]
supports such communication channels.

The replication of shares on all MSPs is important because this
transparent share accounting enables all the miners to calculate the
payout distribution and validate any new payout and coinbase
transactions before signing the syndicate update transaction.

We use a highly efficient BFT reliable broadcast protocol proposed by
https://ieeexplore.ieee.org/abstract/document/1541196[Cachin et. al.]. The
protocol has a communication complexity of stem:[$O(n|F|)$] for
broadcasting data of size stem:[$|F|$] to n nodes connected using a point to
point network.

== Open Access to Replicated Shares

Once a miner starts sending shares to a MSP, the shares are replicated
to the other MSPs. A MSP that receives shares, verifies the shares and
then broadcasting them to the rest of the syndicate. A miner can send
their shares to multiple syndicates by registering with the syndicate.

This results in an open database of shares that all MSPs and other
interested parties can run accounting on. This open access to verified
shares is used to build futures contracts using DLCs to pay miners.

== Transparent and Open Operations

A mining syndicate results in a transparent pool where all syndicate
members validate all other MSPs are working correctly. If
a member is not working according to the agreed upon protocols, the
honest MSPs stop rewarding the dishonest member and will
eventually remove the dishonest member from the syndicate.

The above is made possible by point to point communication between
MSPs as well as the bitcoin contracts between the
MSPs.
