= Syndicate Protocols

[TODO] Update this page

The syndicate and miners follow a number of separate protocols to
enable the system to work together.

== Initial Setup

To start a new syndicate, any member announces their network
address. The threshold and syndicate size is set to one.

Miners that want to join the syndicate initiate their registration
with sole syndicate member and set their stratum end point to the
syndicate member.

.New syndicate with single member
[plantuml, target=intial-setup]
....
@startuml
Miner --> SyndicateMember: Register
SyndicateMember --> Miner: Auth token
Miner <--> SyndicateMember: Stratum auth, notify, submit
"Miner/Validtor" <-- SyndicateMember: Share broadcasts
@enduml
....

At this point, the sole syndicate member acts like a centralised pool
operator, with transparent share accounting.

== New Syndicate Member

To join the syndicate, a new member has to lock in capital in to a
bitcoin transaction signed by the Syndicate using a Schnorr threshold
signautre. A successfully signed transaction signifes that a threshold
of the existing syndicate member agree to the new member joining.

The only criterion available for the existing syndicate members is the
amount of new capital the new member is bringing to the syndicate.

Each syndicate can decide the policies they want to adopt for
admitting new members by agreeing on the minimum and maximum bitcoin
that each member locks into the syndicate. This value is agreed out of
band and configured at syndicate start up time.

.New syndicate member
[plantuml, target=intial-setup]
....
@startuml
NewSyndicateMember --> ExistingMember: Join Request
ExistingMember <--> Syndicate: Reliable broadcast of Join Request
ExistingMember --> NewSyndicateMember: New funding tx (unsigned)
NewSyndicateMember --> ExistingMember: Partially signed funding tx
NewSyndicateMember <--> Syndicate: Run FROST to sign new tx
@enduml
....

== Syndicate Member Exit

Similar to the protocol followed to add a new member to the syndicate,
the syndicate members create a new transaction with updated
balances. The member leaving the syndicate is part of the party that
runs the threshold signature instance to sign the input spending the
previous syndicate output.

== Syndicate Member Failures

If a member fails (say is unresponsive), the syndicate continues to
operate as normal. If more than a threshold number of syndicate
members fail, the pool reaches end of life and all syndicate members
along with miners can claim their outputs after the timeout expiry.

See section on Bitcoin Contracts to see how the transactions are
structured.

