
= Mining Syndicate
Kulpreet Singh, @jungly
:toc:

Mining syndicate resists mining centralisation by providing the
services of a reducing variance for miners, building blocktemplates,
and making miner payouts using secure multi party computation
protocols.

There are two types of parties in the system.

. Miners - running mining facilities and do not need to run bitcoin node.
. Syndicate members - run bitcoin node, generate block templates and sign miner payout transactions. 

Miners register using any syndicate member and communicate with the
syndicate using stratum (v1/v2) protocol.

Syndicate members take on most of the complexity in this
design. Here's a list of responsibilities the syndicate members take
on:

. Build block templates.
. Run stratum servers that miners use to generate shares.
. Run consistent share accounting by using state replication across the members.
. Sign miner payout transactions using Schnorr threshold signatures.

The coinbase and payout transaction are constructed such that neither
the miner nor any syndicate member can steal or deny progress. As
members join the syndicate the threshold requirement for the number of
honest parties is increased.

== Objectives

The mining syndicate based design meets the following goals:

. Transparent share accounting.
. Independent blocktemplate generation by syndicate members.
. Guaranteed payouts for miners independent of blocktemplate used.
. Fee negotiation between syndicate members and miners.

== System Overview

The diagarm below shows how the miners and syndicate members
communicate. Note, there is no peer to peer communication between
miners. Only the syndicate members use p2p communication for
eventually consistent state replication.

Miners register with any syndicate member, after which they can
communicate with any of the syndicate members to receive stratum
messages and send shares.

[plantuml, target=overview]
....
@startuml C4_Elements
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(miner1, "Miner 1", "Mining Operation")
Person(miner2, "Miner 2", "Mining Operation")
Person(miner3, "Miner 3", "Mining Operation")
Person(miner4, "Miner 4", "Mining Operation")

System_Boundary(s, "Syndicate") {
    Person(syndicate_a, "Member A", "Syndicate member")
    Person(syndicate_b, "Member B", "Syndicate member")
    Person(syndicate_c, "Member C", "Syndicate member")
}

BiRel_D(miner1, syndicate_a, "Uses", "Stratum")
BiRel_D(miner2, syndicate_a, "Uses", "Stratum")
BiRel_D(miner2, syndicate_a, "Uses", "Stratum")
BiRel_D(miner3, syndicate_b, "Uses", "Stratum")
BiRel_D(miner4, syndicate_b, "Uses", "Stratum")

BiRel_R(syndicate_a, syndicate_b, "replication", "p2p commnication")
BiRel_R(syndicate_a, syndicate_c, "replication", "p2p communication")
BiRel_D(syndicate_b, syndicate_c, "replication", "p2p communication")

@enduml
....

=== Syndicate Operation

The syndicate members run all the services that pool operators need
to run. The difference is the the syndicate is transparent and all members can
verify correct operations of all other members.

.Syndicate Member Responsibilites
. Run a node that can handle the share validation at scale.
. Run stratum interfaces for miner interaction.
. Expose miner registration interface.
. Generate block templates and the stratum work 
. Contribute capital that is used to pay miners.
. Generate block templates and 


The capital required to fund the pool is distributed across the
syndicate memebers and more importantly the syndicate results in a
transparent pool where all syndicate members and miners can validate
all syndicate members are working correctly. If a member is not
working according to the agreed upon protocols, the honest syndicate
members stop rewarding the dishonest member and will eventually remove
the dishonest member from the syndicate.

The above is made possible by point to point communication between
syndicate members as well as bitcoin contracts between the syndicate
members and miners signed using FROST threshold signatures generated
by the syndicate.

When a new member wants to join a syndicate, the existing members will
reduce their earnings with no guarantees that the new member will be
able to keep up with share validation. The syndicate has no incentives
to allow new syndicate members. However, as the pool grows, and blocks
are found more frequently, the syndicate will need more capital and to
keep functionining.

TODO: Capital calculation.

// [plantuml, target=frost-overview]
// ....
// @startuml
// !include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Dynamic.puml

// Container(new_member, "New Member", "Potential Syndicate member")
// System_Boundary(syndicate, "Syndicate") {
//     Container(syndicate_a, "Member A", "Syndicate member")
//     Container(syndicate_b, "Member B", "Syndicate member")
//     Container(syndicate_c, "Member C", "Syndicate member")
// }    

// Rel_D(new_member, syndicate_a, "Request to Join with capital offered", "Confidential channel")

// Rel(syndicate_a, syndicate_b, "Forward join request", "Confidential channel")
// Rel(syndicate_a, syndicate_c, "Forward join request", "Confidential channel")

// Rel(syndicate_a, syndicate_b, "Run FROST protocol", "Confidential channel")
// Rel(syndicate_a, syndicate_b, "Run FROST protocol", "Confidential channel")
// Rel(syndicate_b, syndicate_c, "Run FROST Protocol", "Confidential channel")


// @enduml
// ....


== Comparison With Centralised Pools

.Pros
. Diverse blocktemplates.
. Resilience - as long a threshold number of members are reachable, the syndicate can continue to make progress.
. Transparent share accounting - miners can validate their payouts are correct.
  . Miners (or anyone) can run tools we provide to monitor the
  syndicate for payout fairness.

.Cons
. PPLNS instead of FPPS

== Comparison With P2P Pools

.Pros
. Miners don't need to run any servers or run any validation at all.
. Zero friction to switch to Syndicated Mining from centralised pools.
. No need for p2p communication between miners - scale depends only on the ability to scale the syndicate p2p communication.
. No consensus required between miners on the state of shares generated.

.Cons
. Block template generation is managed by syndicate members.
  . However, anyone can join the syndicate and provide block
  templates, including miners themselves.


== Syndicate Protocols

The syndicate and miners follow a number of separate protocols to
enable the system to work together.

=== Initial Setup

To start a new syndicate, any member announces their network
address. The threshold and syndicate size is set to one.

Miners that want to join the syndicate initiate their registration
with sole syndicate member and set their stratum end point to the
syndicate member.

.New syndicate with single member
[plantuml, target=intial-setup]
....
@startuml
Miner --> SyndicateMember: Register
SyndicateMember --> Miner: Auth token
Miner <--> SyndicateMember: Stratum auth, notify, submit
"Miner/Validtor" <-- SyndicateMember: Share broadcasts
@enduml
....

At this point, the sole syndicate member acts like a centralised pool
operator, with transparent share accounting.

=== New Syndicate Member

To join the syndicate, a new member has to lock in capital in to a
bitcoin transaction signed by the Syndicate using a Schnorr threshold
signautre. A successfully signed transaction signifes that a threshold
of the existing syndicate member agree to the new member joining.

The only criterion available for the existing syndicate members is the
amount of new capital the new member is bringing to the syndicate.

Each syndicate can decide the policies they want to adopt for
admitting new members by agreeing on the minimum and maximum bitcoin
that each member locks into the syndicate. This value is agreed out of
band and configured at syndicate start up time.

.New syndicate member
[plantuml, target=intial-setup]
....
@startuml
NewSyndicateMember --> ExistingMember: Join Request
ExistingMember <--> Syndicate: Reliable broadcast of Join Request
ExistingMember --> NewSyndicateMember: New funding tx (unsigned)
NewSyndicateMember --> ExistingMember: Partially signed funding tx
NewSyndicateMember <--> Syndicate: Run FROST to sign new tx
@enduml
....

=== Syndicate Member Exit

Similar to the protocol followed to add a new member to the syndicate,
the syndicate members create a new transaction with updated
balances. The member leaving the syndicate is part of the party that
runs the threshold signature instance to sign the input spending the
previous syndicate output.

=== Syndicate Member Failures

If a member fails (say is unresponsive), the syndicate continues to
operate as normal. If more than a threshold number of syndicate
members fail, the pool reaches end of life and all syndicate members
along with miners can claim their outputs after the timeout expiry.

See section on Bitcoin Contracts to see how the transactions are
structured.

=== New Miner Registration

A miner register with any of the syndicate members by following the
protocol to create a new authentication token. This can follow any of
the well known protocols like OAuth. The miner submits a public key to
which it should receive payouts.

A miner can obtain a similar authentication token from multiple
syndicate members. The miner should use the same public key to
register with multiple syndicate members.

Using this authentication token, the miner can open a communication
channel to send and receive stratum messages to the syndicate members.

At the end of the miner registration, the miner is in a position to
start sending shares to the syndicate.

.New Miner Registration
[plantuml, target=intial-setup]
....
@startuml

group Syndicate Member 1
NewMiner --> SyndicateMember_1: Register
NewMiner <-- SyndicateMember_1: Auth token 1
NewMiner --> SyndicateMember_1: Submit public key

NewMiner <--> SyndicateMember_1: Stratum communication
end

group Syndicate Member 2
NewMiner --> SyndicateMember_2: Register using HTTP API
NewMiner <-- SyndicateMember_2: Auth token 2
NewMiner --> SyndicateMember_2: Submit public key

NewMiner <--> SyndicateMember_2: Stratum communication
end
@enduml
....

.Funding Transaction
[plantuml, target=funding-tx]
....
@startuml
object Foo
map Bar {
  abc=>
  def=>
}
object Baz

Bar::abc --> Baz : Label one
Foo --> Bar::def : Label two
@enduml
....

=== Submit Shares to Syndicate: Stratum

The miner signs the shares it submits to the syndicate members. Miners
will use a proxy for signing their shares. The shares are signed by
using the same public key that the miner registered for receiving
payouts.

TIP: The signing of shares and using the proxy is optional.

If the miner does not sign the shares, then it is trusting the
syndicate member to not steal their shares. However, if the syndicate
member steals the shares the miners can observe this by subscribing to
the syndicate p2p broadcast that replicates shares across the
syndicate and observing all the shares the syndicate is receiving.

=== Syndicate Network

The syndicate members open a point to point to connection with all
other syndicate members. This channels is authenticated and
confidential.

Each syndicate member sends the following messages to all other
syndicate members:

. New block template it is working on
. The stratum job it sends to miners
. All shares received from all miners
. Requests by new syndicate members
. Miner public key once it is registered with the syndicate member
. Requests received from miners to leave the pool

The messages above will result in subsantial amount of network
traffic. The syndicate members also validate all the shares received
from other syndicate members.

The replication of shares on all syndicate members is important
because this transparent share accounting enables all the miners to
calculate the payout distribution and validate any new payout and
coinbase transactions before signing the syndicate update transaction.

=== Share Replication and Accounting

Once a miner starts sending shares to a syndicate member, the shares
are replicated to the other syndicate members. A syndicate member that
receives shares, verifies the shares before broadcasting it to the
rest of the syndicate.

A miner can send their shares to multiple syndicates by registering
with the syndicate.


=== Blocktemplate Generation
=== Payout Mechanism
=== Miner Exit

== Coinbase, Blocktemplates and Payouts

The key component that validates the proposal is how coinbases and
blocktemplates are constructed by syndicate members and how payouts
are made to miners.

.Payout sub-system requirements
. Miners can unilaterally exit.
. Syndicate make progress as long as threshold number of members are honest.
. Miners receive payout for all shares using the PPLNS distribution.
. Syndicate members can't steal shares of miners.
